CREATE TABLE forum (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    mensagem TEXT NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    aluno VARCHAR(255) NOT NULL,
    status ENUM('NAO_RESPONDIDO', 'RESPONDIDO') DEFAULT 'NAO_RESPONDIDO',
    respostas TEXT
);